vich_uploader:
    db_driver: orm

    mappings:
        materials:
            uri_prefix: /images/materials
            upload_destination: '%kernel.project_dir%/public/images/materials'
        receipts:
            uri_prefix: /images/receipts
            upload_destination: '%kernel.project_dir%/public/images/receipts'
