---
deployment:
  tasks:
    - export DEPLOYPATH=/home-wh/cweufdea/public_html/
    - /usr/local/bin/composer install
    - /bin/cp -r web/* $DEPLOYPATH
    - SET APP_ENV=prod
    - composer install --no-dev --optimize-autoloader
    - composer dump-autoload --optimize --no-dev --classmap-authoritative
    - /bin/cp node_modules\.bin\encore production
    - /bin/cp bin
    - /bin/cp config
    - /bin/cp src
    - /bin/cp templates
    - /bin/cp translations
    - /bin/cp vendor
    - /bin/cp var
    - php bin/console doctrine:migrations:migrate
